import { addBuildLog, updateProject, encryptObject } from '@/lib';

export async function githubAgent(
  projectId: string,
  userId: string,
  appName: string,
  codebase: Record<string, string>
): Promise<{ repoUrl: string; error?: string }> {
  await addBuildLog(projectId, 'github', 'Creating GitHub repository...', 'info');
  await updateProject(projectId, { current_step: 'github', progress: 70 });

  const token = process.env.GITHUB_ACCESS_TOKEN;
  if (!token) {
    const error = 'GITHUB_ACCESS_TOKEN not configured';
    await addBuildLog(projectId, 'github', error, 'error');
    return { repoUrl: '', error };
  }

  try {
    // Create repo
    const repoName = appName.toLowerCase().replace(/[^a-z0-9-]/g, '-').substring(0, 30);
    
    const createRes = await fetch('https://api.github.com/user/repos', {
      method: 'POST',
      headers: {
        Authorization: `Bearer ${token}`,
        'Content-Type': 'application/json',
        Accept: 'application/vnd.github+json',
      },
      body: JSON.stringify({
        name: repoName,
        description: `Generated by OPS AI DEV - ${appName}`,
        private: false,
        auto_init: false,
      }),
    });

    if (!createRes.ok) {
      const err = await createRes.text();
      throw new Error(`GitHub API error: ${err}`);
    }

    const repo = await createRes.json();
    const repoUrl = repo.html_url;

    await addBuildLog(projectId, 'github', `Created repo: ${repoUrl}`, 'info');
    await updateProject(projectId, { repo_url: repoUrl });

    // Generate tree for bulk upload
    const tree = Object.entries(codebase).map(([path, content]) => ({
      path,
      mode: '100644' as const,
      type: 'blob' as const,
      content,
    }));

    // Get default branch
    const branchRes = await fetch(repo.branches_url.replace('{/branch}', ''), {
      headers: { Authorization: `Bearer ${token}` },
    });
    
    if (!branchRes.ok) {
      throw new Error('Failed to get branch info');
    }
    
    const branchData = await branchRes.json();
    const baseSha = branchData[0]?.commit?.sha;

    if (!baseSha) {
      throw new Error('No base commit found');
    }

    // Create tree
    const treeRes = await fetch(`${repo.trees_url.replace('{/sha}', '')}`, {
      method: 'POST',
      headers: {
        Authorization: `Bearer ${token}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        base_tree: baseSha,
        tree,
      }),
    });

    if (!treeRes.ok) {
      throw new Error('Failed to create tree');
    }

    const treeData = await treeRes.json();

    // Create commit
    const commitRes = await fetch(repo.commits_url.replace('{/sha}', ''), {
      method: 'POST',
      headers: {
        Authorization: `Bearer ${token}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        message: 'Initial commit - Generated by OPS AI DEV',
        tree: treeData.sha,
        parents: [baseSha],
      }),
    });

    if (!commitRes.ok) {
      throw new Error('Failed to create commit');
    }

    const commit = await commitRes.json();

    // Update reference
    const updateRes = await fetch(repo.git_refs_url.replace('{/sha}', '/heads/main'), {
      method: 'PATCH',
      headers: {
        Authorization: `Bearer ${token}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        sha: commit.sha,
        force: false,
      }),
    });

    if (!updateRes.ok) {
      // Try master branch
      await fetch(repo.git_refs_url.replace('{/sha}', '/heads/master'), {
        method: 'PATCH',
        headers: {
          Authorization: `Bearer ${token}`,
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          sha: commit.sha,
          force: false,
        }),
      });
    }

    await addBuildLog(projectId, 'github', `Pushed ${Object.keys(codebase).length} files`, 'info');

    return { repoUrl };
  } catch (err) {
    const error = err instanceof Error ? err.message : String(err);
    await addBuildLog(projectId, 'github', `Failed: ${error}`, 'error');
    return { repoUrl: '', error };
  }
}
